language: swift
osx_image: xcode11.2
before_install:
  - gem install xcpretty
before_script:
  - set -o pipefail
script:
  - xcodebuild clean -project VKPinCodeView/VKPinCodeView.xcodeproj && xcodebuild build -project VKPinCodeView/VKPinCodeView.xcodeproj -scheme VKPinCodeViewExample -configuration Debug -sdk iphonesimulator | xcpretty -c

branches:
  only:
  - master
notifications:
  email: false
